title: Cinder
subtitle: "Cinder for Game Development."
description: "A Game Development Template."
author: Cinder
language: cn
timezone: UTC

url: https://g-cinder.github.io/Memoranda
root: /Memoranda/

theme: navy-s

highlight:
  enable: true
  line_number: false

disqus_shortname: Memoranda
github: g-cinder.github.io/Memoranda