title: Ferry
subtitle: "A lightweight server develop framework for golang."
description: "A lightweight server develop framework for golang."
author: MuGuangyi
language: en
timezone: UTC

url: https://muguangyi.github.io/ferry.io
root: /ferry.io/

theme: navy-s

highlight:
  enable: true
  line_number: false

disqus_shortname: ferry.io
github: muguangyi/ferry